openapi: 3.1.0
info:
  title: Workflow API Gateway
  version: 0.1.0
servers:
  - url: http://localhost:4000
paths:
  /health:
    get:
      summary: Gateway health
      responses:
        '200':
          description: OK
  /aggregate/health:
    get:
      summary: Aggregate downstream service health
      responses:
        '200':
          description: OK
  /secure/ping:
    get:
      summary: Authenticated ping
      security:
        - bearerAuth: []
      responses:
        '200': { description: OK }
  /secure/admin:
    get:
      summary: Admin-only check
      security:
        - bearerAuth: []
      responses:
        '200': { description: OK }
  /secure/me:
    get:
      summary: Current user via auth-service
      security:
        - bearerAuth: []
      responses:
        '200': { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
